openapi: 3.0.3
info:
  title: API documentation
  version: 1.0.0
servers:
  - url: http://localhost:8081/
tags:
  - name: User
paths:
  /users:
    $ref: "./resources/user.yaml#/UsersGetPath"
  /user/get-by-id/{id}:
    $ref: "./resources/user.yaml#/UserGetPathWithID"
  /user/create:
    $ref: "./resources/user.yaml#/UserCreatePath"
  /user/update/{id}:
    $ref: "./resources/user.yaml#/UserUpdatePathWithID"
  /user/delete/{id}:
    $ref: "./resources/user.yaml#/UserDeletePathWithID"

components:
  schemas:
    User:
      $ref: "./schemas/user_schema.yaml"
